### ISSUE TITLE
How about PyData Amsterdam?

### ISSUE THREAD

**Issue by sujitpal** [DataTau/datascience-anthology-pydata#12]
There was one in 2016:
http://pydata.org/amsterdam2016/

and they are planning another one for 2017.
https://twitter.com/pydataamsterdam/status/775386695122489345

Would this qualify for inclusion here?

**Comment by rsivapr** [comment]
Hi Sujit! 

Yes. Definitely. Feel free to send a PR.

**Comment by sujitpal** [comment]
Thank you. PR sent.

**Comment by rsivapr** [comment]
So good. Feel free to add your name and link in the contributions list please! I'll accept it after that

**Comment by sujitpal** [comment]
Done now.

**Comment by sujitpal** [comment]
@rsivapr PR should be complete now, please let me know if I need to do anything else for it to be accepted.

**Comment by sujitpal** [comment]
closing.
